-- 총주문량 3000 이상
-- 과일 성분
-- 맛을 총주문량 순으로 내림차순
SELECT f.FLAVOR
FROM FIRST_HALF f
LEFT JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
WHERE f.TOTAL_ORDER >= 3000 AND i.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;