-- 22년 10월
-- 댓글 작성일 기준 오름
-- 같으면 게시글 제목 기준
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, r.CREATED_DATE
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_REPLY r
ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE LIKE '2022-10-%'
ORDER BY r.CREATED_DATE, b.TITLE;