-- 코드를 입력하세요
WITH MAXP AS ( 
    SELECT CATEGORY, MAX(PRICE) AS MX
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT f.CATEGORY, f.PRICE AS MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN MAXP m 
    ON f.CATEGORY = m.CATEGORY AND f.PRICE = m.MX
ORDER BY MAX_PRICE DESC;